[[main]]
name = "Utility"
url = "#utility"
weight = 5
[[main]]
name = "Traits"
url = "/"
weight = 10
[[main]]
name = "FAQ"
url = "/"
weight = 15
[[main]]
name = "Tokenomics"
url = "/tokenomics"
weight = 20
[[main]]
name = "Tour"
url = "/tour-dates"
weight = 30


[[social]]
name = "Linktr.ee"
url = "https://linktr.ee/bandhorses"
weight = 10

[[social]]
name = "Twitter"
url = "https://twitter.com/bandhorsesNFT"
weight = 20
[[social]]
name = "Discord"
url = "https://discord.gg/UyaJspUaSZ"
weight = 30
[[social]]
name = "Blog"
url = "https://medium.com/@bandhorses"
weight = 40
[[social]]
name = "pinterest"
url = "https://www.pinterest.com/bandhorses/"
weight = 50
[[social]]
name = "Pinterest"
url = "https://www.pinterest.com/bandhorses/"
weight = 60
[[social]]
name = "d.tube"
url = "https://d.tube/c/bandhorses00"
weight = 60
[[social]]
name = "Vimeo"
url = "https://vimeo.com/user165460933"
weight = 60
