[[main]]
name = "Utility"
url = "#utility"
weight = 5
[[main]]
parent = "Utility"
name = "Traits"
url = "/utility/rarity"
weight = 10
[[main]]
parent = "Utility"
name = "FAQ"
url = "/utility/faq"
weight = 15
[[main]]
name = "WAGMI"
url = "#WAGMI"
weight = 20
[[main]]
parent = "WAGMI"
name = "Responsible Frenz"
url = "/wagmi/sr"
weight = 22
[[main]]
parent = "WAGMI"
name = "Tokenomics"
url = "/wagmi/tokenomics"
weight = 24
[[main]]
name = "Fun Tour"
url = "/tour-dates"
weight = 30


[[footer]]
name = "Partnership"
url = "https://form.jotform.com/220570593472962"
weight = 10

[[social]]
name = "link-45deg"
url = "https://links.bandhorses.com"
weight = 10
[[social]]
name = "twitter"
url = "https://twitter.com/bandhorsesNFT"
weight = 20
# [[social]]
# name = "pinterest"
# url = "https://www.pinterest.com/bandhorses/"
# weight = 30
# [[social]]
# name = "discord"
# url = "https://discord.gg/UyaJspUaSZ"
# weight = 40
# [[social]]
# name = "medium"
# url = "https://medium.com/@bandhorses"
# weight = 50
# [[social]]
# name = "youtube"
# url = "https://d.tube/c/bandhorses00"
# weight = 60
# [[social]]
# name = "vimeo"
# url = "https://vimeo.com/user165460933"
# weight = 70
